version: 2.1
executors:
  docker-executor:
    docker:
      - image: node
jobs:
  automated-api-tests:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Apifox CLI
          command: npm install -g apifox-cli
      - run:
          name: Running Test Scenario
          command: apifox run https://api.apifox.com/api/v1/projects/1320441/api-test/ci-config/409476/detail?token=x9wRvPCs21ofE3FW8439Xp -r html,cli
workflows:
  version: 2
  build:
    jobs:
      - automated-api-tests
