version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:2021.04
jobs:
  automated-api-tests:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Apifox CLI
          command: npm install -g apifox-cli
      - run:
          name: Running Test Scenario
          command: apifox run http://192.168.10.208:5777/api/v1/projects/345286/api-test/ci-config/345136/detail?token=x9txg4nbJoKdVpWyBlnIjs -r html,cli
workflows:
  version: 2
  build:
    jobs:
      - automated-api-tests
